@baseUrl = http://localhost:3000

### Read all movies
GET {{baseUrl}}/films

### Read all filtered movies
GET {{baseUrl}}/films?minimum-duration=120

### Read one movie
GET {{baseUrl}}/films/1

### Create one movie
POST {{baseUrl}}/films/
Content-Type: application/json

{
    "title":"Ratatouille",
    "duration":200,
    "budget":1,
    "link":"https://fr.wikipedia.org/wiki/Ratatouille_(film)"
}

### Delete one movie
DELETE {{baseUrl}}/films/4

### Update the movie identified by 3
PATCH {{baseUrl}}/films/3
Content-Type: application/json

{
    "title":"Pirate des Caraïbes"
}

### Update the movie identified by 2
PUT {{baseUrl}}/films/2
Content-Type: application/json

{
    "title":"Pirate des Caraïbes",
    "duration":250,
    "budget":10,
    "link":"flemme"
}

### Create the movie identified by 4
PUT {{baseUrl}}/films/4
Content-Type: application/json

{
    "title":"Avatar",
    "duration":500,
    "budget":100,
    "link":"https://google.com/"
}